/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicauca.openmarket.presentation;


import co.edu.unicauca.openmarket.access.CategoryRepository;
import co.edu.unicauca.openmarket.domain.service.ProductService;
import co.edu.unicauca.openmarket.domain.service.CategoryService;
import co.edu.unicauca.openmarket.access.ProductRepository;

/**
 *
 * @author dilan
 */
public class GUIStart extends javax.swing.JFrame {

    
    
    /**
     * Creates new form GUIStart
     */
    public GUIStart() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenida = new javax.swing.JLabel();
        jSeparatorMenu = new javax.swing.JSeparator();
        jPanelAgregarProd = new javax.swing.JPanel();
        jLabelAgregarCat = new javax.swing.JLabel();
        jPanelAgregarCat = new javax.swing.JPanel();
        jLabelAgregarProd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(595, 289));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelBienvenida.setFont(new java.awt.Font("Segoe UI Emoji", 1, 30)); // NOI18N
        jLabelBienvenida.setText("Bienvenid@");
        getContentPane().add(jLabelBienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 40));

        jSeparatorMenu.setName("jSeparatorMenu"); // NOI18N
        getContentPane().add(jSeparatorMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 580, 10));

        jPanelAgregarProd.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAgregarProd.setForeground(new java.awt.Color(204, 204, 204));

        jLabelAgregarCat.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabelAgregarCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarCat.setText("Categoria"); // NOI18N
        jLabelAgregarCat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregarCat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarCatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarProdLayout = new javax.swing.GroupLayout(jPanelAgregarProd);
        jPanelAgregarProd.setLayout(jPanelAgregarProdLayout);
        jPanelAgregarProdLayout.setHorizontalGroup(
            jPanelAgregarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelAgregarCat, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanelAgregarProdLayout.setVerticalGroup(
            jPanelAgregarProdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarProdLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAgregarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelAgregarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 230, 90));

        jPanelAgregarCat.setBackground(new java.awt.Color(204, 204, 204));
        jPanelAgregarCat.setForeground(new java.awt.Color(204, 204, 204));

        jLabelAgregarProd.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabelAgregarProd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAgregarProd.setText("Producto"); // NOI18N
        jLabelAgregarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAgregarProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAgregarProdMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelAgregarCatLayout = new javax.swing.GroupLayout(jPanelAgregarCat);
        jPanelAgregarCat.setLayout(jPanelAgregarCatLayout);
        jPanelAgregarCatLayout.setHorizontalGroup(
            jPanelAgregarCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarCatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelAgregarCatLayout.setVerticalGroup(
            jPanelAgregarCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAgregarCatLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelAgregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanelAgregarCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 230, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelAgregarCatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarCatMouseClicked
        CategoryRepository categoryRepository = new CategoryRepository();
        CategoryService categoryService = new CategoryService(categoryRepository);
        
        ProductRepository productRepository = new ProductRepository();
        ProductService productService = new ProductService(productRepository);
        GUICategorys objGuiCategorys = new GUICategorys(categoryService, productService);
        objGuiCategorys.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelAgregarCatMouseClicked

    private void jLabelAgregarProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAgregarProdMouseClicked
        ProductRepository productRepository = new ProductRepository();
        CategoryRepository categoryRepository = new CategoryRepository();
        ProductService productService = new ProductService(productRepository);
        CategoryService categoryService = new CategoryService(categoryRepository);
        
        GUIProducts instance = new GUIProducts(productService, categoryService); //OJO CON ESTO
        instance.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelAgregarProdMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAgregarCat;
    private javax.swing.JLabel jLabelAgregarProd;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JPanel jPanelAgregarCat;
    private javax.swing.JPanel jPanelAgregarProd;
    private javax.swing.JSeparator jSeparatorMenu;
    // End of variables declaration//GEN-END:variables
}
